### PR TITLE
Radioactive decay node for review

### PR DESCRIPTION
**Pull request by TheDoctorRAB**

### CODE REVIEW

**Comment by gonuke** [comment]
This is longer and broader than I would choose... I would split this into one node per learning objective.  It's easier to review that way, too, since it's easier to assess whether there is at least one assessment per objective

**Comment by TheDoctorRAB** [comment]
Was that something we discussed before (one learning objective per node)? It doesn't matter to me either way, but I don't remember.

**Comment by gonuke** [comment]
No, we didn't decide anything.  We specifically decided to NOT decide in the abstract, and to wait until we had concrete examples.  So my comments are more to open a conversation with this as a concrete example.

**Comment by TheDoctorRAB** [comment]
This one could be split, and that's ok with me, but I'm just concerned we'd be getting unwieldy with the nodes by sticking to one-to-one.

**Comment by TheDoctorRAB** [comment]
I'll close this and split the node.

**Pull request closed without merging**
