### PR TITLE
Style guide change because we aren't using info.yml files anymore. 

### PR DESCRIPTION
**Pull request by TheDoctorRAB**

### CODE REVIEW

**Comment by gonuke** [comment]
This needs to be rebased with the change merged in #37

**Comment by TheDoctorRAB** [comment]
I don't know how to do that. I can just kill this for now if it's a problem.

**Comment by TheDoctorRAB** [comment]
Is this one closed now? Or should it be?

**Comment by katyhuff** [comment]
yes.

**Pull request closed without merging**
