### PR TITLE
Shell model node for review 

### PR DESCRIPTION
**Pull request by TheDoctorRAB**

### CODE REVIEW

**Comment by gonuke** [comment]
I think you need to include the prerequisite, even if it's a mostly-empty boundary node.

**Comment by TheDoctorRAB** [comment]
How broad could that be? Undergraduate chemistry?

**Comment by TheDoctorRAB** [comment]
How broad could that be? Undergraduate chemistry?

**Comment by gonuke** [comment]
I think we discussed that the boundary nodes can be quite broad.  But again, we're forging new ground here, so it's a point of discussion as much as anything

**Comment by TheDoctorRAB** [comment]
That's ok. I wanted to work more on the boundary nodes because I have a lot of basic material from my intro course.

**Comment by TheDoctorRAB** [comment]
I'll close this because I have to change the node meta information based on the new contributions document.

**Pull request closed without merging**
